version: '3.8'

services:
  redis:
    image: redis:7.2.1-alpine
    hostname: redis
    restart: always
    env_file: .env
    ports:
      - '${REDIS_PORT}:${REDIS_PORT}'
  webapp:
    container_name: webapp
    restart: always
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile.app
    ports:
      - 5000:5000
    depends_on:
      - redis
#      - db
    volumes:
      - ./github-app:/app/github-app
#  db:
#    image: postgres:14-alpine
#    volumes:
#      - postgres_data:/var/lib/postgresql/data/
#    env_file: .env
#    environment:
#      - POSTGRES_DB=${DB_NAME}
#      - POSTGRES_USER=${DB_USERNAME}
#      - POSTGRES_PASSWORD=${DB_PASS}
#  nginx:
#    container_name: nginx
#    restart: always
#    image: "nginx:latest"
#    ports:
#      - "85:85"
#    volumes:
#      - ./nginx:/etc/nginx/conf.d
#    networks:
#      - web_network
#    depends_on:
#      - appseed-app
