version: '3.8'

services:
  redis:
    image: redis:7.2.1-alpine
    hostname: redis
    restart: always
    env_file: .env
    ports:
      - '${REDIS_PORT}:${REDIS_PORT}'
  webapp:
    container_name: webapp
    restart: always
    env_file: .env
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        DEBUG: ${DEBUG}
    command: ./start-webapp
    ports:
      - 5000:5000
    depends_on:
      - redis
#      - db
    volumes:
      - ./otterdog:/app/otterdog
      - ./github-app:/app/github-app

  celery_worker:
    container_name: celery-worker
    restart: always
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        DEBUG: ${DEBUG}
    command: ./start-celery-worker
    env_file: .env
    depends_on:
      - redis
    volumes:
      - ./otterdog:/app/otterdog
      - ./github-app:/app/github-app

  nginx:
    container_name: nginx
    restart: always
    image: "nginx:latest"
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - webapp

#  db:
#    image: postgres:14-alpine
#    volumes:
#      - postgres_data:/var/lib/postgresql/data/
#    env_file: .env
#    environment:
#      - POSTGRES_DB=${DB_NAME}
#      - POSTGRES_USER=${DB_USERNAME}
#      - POSTGRES_PASSWORD=${DB_PASS}
