name: Release
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version'
        required: true
      version-fragment:
        description: 'Version fragment to increase for next development cycle'
        required: true
        default: 'minor'
        type: choice
        options:
          - major
          - minor
          - patch
          - none

env:
  BOT_USER_NAME: eclipse-csi-bot
  BOT_EMAIL: csi-bot@eclipse.org
  PYTHON_VERSION: '3.12'
  POETRY_VERSION: '1.8.4'

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  precheck:
    runs-on: ubuntu-22.04
#    if: github.repository == 'eclipse-csi/otterdog'
    steps:
      - name: "Check ref"
        shell: bash
        run: |
          if [ "${{ github.ref }}" != "refs/heads/main" ]; then
            echo "Release shall only be made from 'main' branch, triggered branch '${{ github.ref_name }}', aborting."
            exit 1
          fi

  release:
    runs-on: ubuntu-22.04
    needs: ['precheck']
    permissions:
      contents: write
    outputs:
      release-version: ${{ steps.prepare-release.outputs.RELEASE_VERSION }}
      release-tag: ${{ steps.prepare-release.outputs.RELEASE_TAG }}
    steps:
      - name: "Setup Bot User"
        run: |
          git config --global user.name '${{ env.BOT_USER_NAME }}'
          git config --global user.email '${{ env.BOT_EMAIL }}'

      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          ref: ${{ github.ref }}

      - uses: actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c # v5.0.0
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - uses: snok/install-poetry@93ada01c735cc8a383ce0ce2ae205a21c415379b # v1.3
        with:
          virtualenvs-in-project: true
          version: ${{ env.POETRY_VERSION }}

      - name: "Install dependencies"
        run: poetry install -v --without dev,typing,docs

      - name: "Run tests"
        run: |
          source $VENV
          pytest -rs tests

      - name: "Prepare release"
        id: prepare-release
        shell: bash
        env:
          RELEASE_VERSION: ${{ github.event.inputs.version }}
        run: |
          PROJECT_VERSION="$(poetry version -s)"

          echo "PROJECT_VERSION=$(echo $PROJECT_VERSION)" >> $GITHUB_OUTPUT
          echo "RELEASE_VERSION=$RELEASE_VERSION" >> $GITHUB_OUTPUT

          echo "Project version: $PROJECT_VERSION"
          echo "Release version: $RELEASE_VERSION"

          if git show-ref --tags --verify --quiet "refs/tags/v${RELEASE_VERSION}"; then
            echo "Release Tag 'v${RELEASE_VERSION}' already exists, aborting."
            exit 1
          fi

          if [ "$PROJECT_VERSION" != "$RELEASE_VERSION" ]; then
            poetry version $RELEASE_VERSION
            git commit -a -m "Releasing version $RELEASE_VERSION"
            git push origin ${{ github.ref }}
          fi

          echo "RELEASE_TAG=v$RELEASE_VERSION" >> $GITHUB_OUTPUT

      - name: "Tag release"
        id: tag-release
        shell: bash
        run: |
          git tag ${{ steps.prepare-release.outputs.RELEASE_TAG }}
          git push origin --tags

  publish:
    needs: ['release']
    permissions:
      actions: read
      contents: write
      id-token: write
      packages: write
    uses: ./.github/workflows/publish.yml
    with:
      release-tag: "${{ needs.release.outputs.release-tag }}"

  prepare-for-next-development-cycle:
    runs-on: ubuntu-22.04
    needs: ['publish']
    permissions:
      contents: write
    if: ${{ github.event.inputs.version-fragment != 'none' }}
    steps:
      - name: Setup Git User
        run: |
          git config --global user.name '${{ env.BOT_USER_NAME }}'
          git config --global user.email '${{ env.BOT_EMAIL }}'

      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          ref: ${{ github.ref }}

      - uses: actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c # v5.0.0
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - uses: snok/install-poetry@93ada01c735cc8a383ce0ce2ae205a21c415379b # v1.3
        with:
          virtualenvs-in-project: true
          version: ${{ env.POETRY_VERSION }}

      - name: Update next development version
        env:
          VERSION_FRAGMENT: ${{ github.event.inputs.version-fragment }}
        run: |
          NEXT_VERSION="$(poetry version ${VERSION_FRAGMENT} -s)"
          poetry version "$NEXT_VERSION".dev0

          git commit -a -m "Prepare for next development cycle"
          git push origin ${{ github.ref }}
